### ISSUE TITLE
feature: /reviewgachaでないidを指定した時にエラーが出るので修正したい

### ISSUE THREAD

**Issue by mamepon2580** [waiwai-developers/waiwaichan#244]

**Comment by mamepon2580** [comment]
error log
```
waiwai-backend    | (Use `node --trace-deprecation ...` to show where the warning was created)
waiwai-backend    | login: waiwaichan#8340
waiwai-backend    | RequestError [HttpError]: Not Found - https://docs.github.com/rest/pulls/pulls#get-a-pull-request
waiwai-backend    |     at fetchWrapper (file:///app/node_modules/@octokit/request/dist-bundle/index.js:119:11)
waiwai-backend    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
waiwai-backend    |     at PullRequestLogic.randomAssign (/app/src/logics/PullRequestLogic.ts:19:14)
waiwai-backend    |     at Client.<anonymous> (/app/src/routes/discordjs/events/SlashCommandRouter.ts:202:8) {
waiwai-backend    |   status: 404,
waiwai-backend    |   request: {
waiwai-backend    |     method: 'GET',
waiwai-backend    |     url: 'https://api.github.com/repos/waiwai-developers/waiwaichan/pulls/242',
waiwai-backend    |     headers: {
waiwai-backend    |       accept: 'application/vnd.github.v3+json',
waiwai-backend    |       'user-agent': 'octokit-core.js/6.1.2 Node.js/22',
waiwai-backend    |       'x-github-api-version': '2022-11-28',
waiwai-backend    |       authorization: 'token [REDACTED]'
waiwai-backend    |     },
waiwai-backend    |     request: { hook: [Function: bound bound register] }
waiwai-backend    |   },
waiwai-backend    |   response: {
waiwai-backend    |     url: 'https://api.github.com/repos/waiwai-developers/waiwaichan/pulls/242',
waiwai-backend    |     status: 404,
waiwai-backend    |     headers: {
waiwai-backend    |       'access-control-allow-origin': '*',
waiwai-backend    |       'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
waiwai-backend    |       'content-encoding': 'gzip',
waiwai-backend    |       'content-security-policy': "default-src 'none'",
waiwai-backend    |       'content-type': 'application/json; charset=utf-8',
waiwai-backend    |       date: 'Sat, 23 Nov 2024 10:52:46 GMT',
waiwai-backend    |       'github-authentication-token-expiration': '2024-12-13 13:20:11 UTC',
waiwai-backend    |       'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
waiwai-backend    |       server: 'github.com',
waiwai-backend    |       'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
waiwai-backend    |       'transfer-encoding': 'chunked',
waiwai-backend    |       vary: 'Accept-Encoding, Accept, X-Requested-With',
waiwai-backend    |       'x-accepted-oauth-scopes': 'repo',
waiwai-backend    |       'x-content-type-options': 'nosniff',
waiwai-backend    |       'x-frame-options': 'deny',
waiwai-backend    |       'x-github-api-version-selected': '2022-11-28',
waiwai-backend    |       'x-github-media-type': 'github.v3; format=json',
waiwai-backend    |       'x-github-request-id': 'B7AA:1C5B9:3DC745:4322A7:6741B3FE',
waiwai-backend    |       'x-oauth-scopes': 'repo',
waiwai-backend    |       'x-ratelimit-limit': '5000',
waiwai-backend    |       'x-ratelimit-remaining': '4997',
waiwai-backend    |       'x-ratelimit-reset': '1732361698',
waiwai-backend    |       'x-ratelimit-resource': 'core',
waiwai-backend    |       'x-ratelimit-used': '3',
waiwai-backend    |       'x-xss-protection': '0'
waiwai-backend    |     },
waiwai-backend    |     data: {
waiwai-backend    |       message: 'Not Found',
waiwai-backend    |       documentation_url: 'https://docs.github.com/rest/pulls/pulls#get-a-pull-request',
waiwai-backend    |       status: '404'
waiwai-backend    |     }
waiwai-backend    |   }
waiwai-backend    | }
```
